### ISSUE TITLE
Bug Fix: SimulationTimestampPstateSet should not record multiple pstate changes for the same time

### ISSUE THREAD

**Issue by ryantanaka** [wrench-project/wrench#100]
@spenceralbrecht pointed out a bug in output from `SimulationOutput::dumpHostEnergyConsumptionJSON()`. If consecutive calls to `Simulation::setPstate()` are made, then the p-state trace from simulation output will show multiple p-states for the same simulated time. So, I need to make sure that when consecutive calls are made to `Simulation::setPstate()` during the same simulated time, only one timestamp is recorded for the final call.

**Comment by henricasanova** [comment]
fixed by ryan and merged
