### ISSUE TITLE
Making message_payloads std::map<std::string, double>

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#102]
After profiling some code, I found that we spend a lot of time in converting strings to double, since we do it for each message payload.  Right now it's not using sscanf. It could be faster using strtod (about a factor 4 faster on my machine).  But really, how about doing those conversions only once or not at all. Two options:

Option #1:  we change the constructor of all services to pass payload lists as maps of string,double (we leave the property list as maps of string,string). Drawback, that's a quite drastic API change, although I doubt others have customized payloads. Also, property lists are not different from message payload lists. But they _are_ different actually, so perhaps that's all good. 

Option #2: we keep the API as it is, but internally store the payloads as something like map<string, pair<string, double>>, or perhaps just map<string, double>. This could be done in the constructor of course.  

I am thinking Optiont #1.

**Comment by rafaelfsilva** [comment]
I also agree that option 1 would be the best here (I think I am the only one using payloads). Option 2 still has the conversion problem (at a lower scale but it will still happen).

**Comment by henricasanova** [comment]
Implemented Option #1 in the henri_failures branch
