### ISSUE TITLE
Making all service pointers shared_ptr

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#103]
now that fault-tolerance is implemented, making all service pointers shared_ptr instead of raw pointers is a good idea to avoid weird segfaults in user/developer code.  This is being explored in the henri_failures_shared_ptr branch.

**Comment by henricasanova** [comment]
In spite of failing tests, some tests pass, including the complicated "whole enchilada" fault-tolerance test. And initial experiments show that the slowdown due to using shared_ptr is minimal (about .5sec slowdown on a test that takes 1min1s, i.e., less than 1 percent).

**Comment by rafaelfsilva** [comment]
@henricasanova, That's great! So at the end the performance loss won't be too bad, and we will gain a lot on usability of the system.

**Comment by henricasanova** [comment]
Here are a few design/API issues to discuss (during a conf call!):

DEVELOPER: unique_ptr -> shared_ptr:
        + all casts will look the same
        - loss of performance

DEVELOPER: remove event->type, failure->type, just be cast-based
        + uniform across the board
        + not duplicating "what class am I?" info since C++ has it
        - perhaps counter-intuitive/awkward to have to "cast and see if nullptr" is returned...
            - But then, users can always use typeid anyway, so why maintain our own types!!?

USER: make Simulation::add a factory
        + NO RAW pointers for the user anywhere (safer)
        + No loss of specifics (i.e., right now adding a Cloud returns a shared_ptr<ComputeService>, "forgetting" it was a Cloud!)
        - many versions of add (addBareMetal(), addCloud() to maintain
            - one version for each public constructor

**Comment by henricasanova** [comment]
Did all the above. no different in speed going from unique_ptr to shared_ptr for messages! (this is because so much other stuff is going on, and also the code is simpler).

**Comment by henricasanova** [comment]
merged into master
