### ISSUE TITLE
Enable pilot job submission for HTCondor service

### ISSUE THREAD

**Issue by rafaelfsilva** [wrench-project/wrench#105]
- [x] Implementation of pilot job support
- [x] Update documentation
- [ ] Implement tests

**Comment by henricasanova** [comment]
While trying a test for this, I become a bit confused. It looks like the HT service will simply start jobs on the next available sub-service (e.g., a BareMetalComputeService). But what happens is that a PilotJob would simply be sent to the next service. And if that service doesn't support pilot jobs, then there is an "doesn' t support pilot job".  So I am not sure what it means for HTCondor to support pilot jobs actually..  The idea is that it simply relays pilot job requests to one of the  subservices? But then it should filter out those services that do not support pilot jobs (and if none does, then too bad, failure). And then, when multiple do, how do we pick?

**Comment by rafaelfsilva** [comment]
I see your confusion. Actually, HTCondor does not make difference between pilot jobs or regular jobs. However, since our implementation makes this clear difference (and callbacks are handled differently). HTCondor matches the first available service to submit the job (assuming all requirements are met), thus no smart decision is made here. If someone wants a very specific dataset, they need to pass it as part of a requirement. Does this make sense to you?

**Comment by henricasanova** [comment]
Ok, so I'll just change the code in HTCondor so that if a pilot job is submitted, those sub-services that do not support pilot jobs are not considered (and  if none does, then some error).  Not sure  what you mean by "dataset"?

**Comment by rafaelfsilva** [comment]
yes, sounds good. "dataset" is most probably a typo ;) I believe I meant to type "behavior"

**Comment by henricasanova** [comment]
Ok, I am working on an htcondor branch trying stuff out. One thing that's now really unclear is how TFCondor works on top of a cloud, because a cloud supports neither pilot nor standard job, it's just a VM creating service, and those VMs support standardjobs.   This is something we can discuss in Denver perhaps :)
