### ISSUE TITLE
Method dumpPlatformGraphJSON crash when routing="Full" without all hosts connected in the XML

### ISSUE THREAD

**Issue by lpottier** [wrench-project/wrench#119]
Hi,

I have noticed that if you set routing="Full" in your platform XML and you do not connect all the hosts together then `dumpPlatformGraphJSON`crashes:
`Uncaught exception nlohmann::detail::type_error: [json.exception.type_error.304] cannot use at() with null`. 
This issue is solved by either specifying routing="Floyd"/routing="Dijkstra" or by connecting each host in the XML, but, it could be nice to throw an exception and/or a warning instead of crashing.

Best,
Loïc Pottier

**Comment by henricasanova** [comment]
thanks for the bug report. I fixed it a bit brutally, i.e., disallowing generating a platform graph whenever the platform is partitioned (i.e., whenever there is no route between at least one pair of hosts).
