### ISSUE TITLE
Service-Specific Job Arguments for HTCondor

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#124]
Different compute services require different service-specific arguments. Say a HTCondor service is on top of BOTH a BareMetalComputeService and a BatchComputeService.  If a standard job is to be submitted to the former, then there is one kind of service-specific arguments. But to the latter there is another kind. So if HTCondor chooses the service, then there is no way for me to know what kind of arguments to provide....

This has to happen in HTCondor in the real world I assume?

**Comment by rafaelfsilva** [comment]
I have investigated this issue in HTCondor documentation, and actually it will require a better implementation for supporting the `grid` universe (https://htcondor.readthedocs.io/en/stable/grid-computing/grid-universe.html?highlight=slurm#). I am closing this issue, and will create a new one to be implemented in the next release.
