### ISSUE TITLE
Feature Request: Augment the set of simulation events in the simulation output

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#13]
What simulation "events" to add:
  - Task start
  - Task failure
  - File copy begins
  - File copy ends
  - File copy failure 

One thing is that with our current design we will sprinkle our code with "add timestamp" everywhere in the code... is there a better way? 

We should also augment the WorkflowTask object to keep track of detailed time info. For starters:
  - task_start_date ( already in there)
  - task_computation_start_date
  - task_computation_end_date

**Comment by ryantanaka** [comment]
@henricasanova, I have a few questions. First, I added some simulation events regarding WorkflowTasks. The `SimulationTimestampTypes.h` now looks like this:

```cpp
#ifndef WRENCH_SIMULATIONTIMESTAMPTYPES_H
#define WRENCH_SIMULATIONTIMESTAMPTYPES_H

namespace wrench {

    class WorkflowTask;

    /**
    * @brief A "task completion event" simulation timestamp
    */
    class SimulationTimestampTask {

    public:

        /***********************/
        /** \cond DEVELOPER    */
        /***********************/

        /**
         * @brief Constructor
         * @param task: a workflow task
         */
        SimulationTimestampTask(WorkflowTask *task) {
            this->task = task;
        }

        ~SimulationTimestampTask() {

        }

        /***********************/
        /** \endcond           */
        /***********************/

        /**
         * @brief Retrieve the task that has completed
         *
         * @return the task
         */
        WorkflowTask *getTask() {
          return this->task;
        }


    private:
        WorkflowTask *task;
    };

    class SimulationTimestampTaskStart : public SimulationTimestampTask {
    public:
        SimulationTimestampTaskStart(WorkflowTask *task) : SimulationTimestampTask(task) {

        }
    };

    class SimulationTimestampTaskFailure : public SimulationTimestampTask {
    public:
        SimulationTimestampTaskFailure(WorkflowTask *task) : SimulationTimestampTask(task) {

        }
    };

    class SimulationTimestampTaskCompletion : public SimulationTimestampTask {
    public:
        SimulationTimestampTaskCompletion(WorkflowTask *task) : SimulationTimestampTask(task) {

        }
    };

};

#endif //WRENCH_SIMULATIONTIMESTAMPTYPES_H
```

And the "sprinkled" code mentioned in the previous comment ends up looking like this in the `WorkunitMulticoreExecutor.cpp`:

```cpp
  /**
     * @brief Simulate work execution
     *
     * @param work: the work to perform
     */
    void
    WorkunitMulticoreExecutor::performWork(Workunit *work) {

//      std::set<WorkflowFile* > files_stored_in_scratch = {};

      /** Perform all pre file copies operations */
     .
     .
     .
     .

      /** Perform all tasks **/
      for (auto task : work->tasks) {

        task->setInternalState(WorkflowTask::InternalState::TASK_RUNNING);

        // Read  all input files
        WRENCH_INFO("Reading the %ld input files for task %s", task->getInputFiles().size(), task->getID().c_str());
        try {
            StorageService::readFiles(task->getInputFiles(),
                                      work->file_locations,
                                      this->scratch_space, files_stored_in_scratch);
        } catch (WorkflowExecutionException &e) {
          task->setInternalState(WorkflowTask::InternalState::TASK_FAILED);
            this->simulation->getOutput().addTimestamp<SimulationTimestampTaskFailure>(new SimulationTimestampTaskFailure(task));
          throw;
        }

        // Run the task's computation (which can be multicore)
        WRENCH_INFO("Executing task %s (%lf flops) on %ld cores (%s)", task->getID().c_str(), task->getFlops(), this->num_cores, S4U_Simulation::getHostName().c_str());
        task->setStartDate(S4U_Simulation::getClock());

        // Generate a SimulationTimestampTaskStart
        this->simulation->getOutput().addTimestamp<SimulationTimestampTaskStart>(new SimulationTimestampTaskStart(task));


        try {
          runMulticoreComputation(task->getFlops(), task->getParallelEfficiency());
        } catch (WorkflowExecutionEvent &e) {
          task->setInternalState(WorkflowTask::InternalState::TASK_FAILED);
          this->simulation->getOutput().addTimestamp<SimulationTimestampTaskFailure>(new SimulationTimestampTaskFailure(task));
            throw;
        }

        WRENCH_INFO("Writing the %ld output files for task %s", task->getOutputFiles().size(), task->getID().c_str());

        // Write all output files
         for (auto file_copy : work->pre_file_copies) {
        WorkflowFile *file = std::get<0>(file_copy);
        //Even in the pre-file copies, the src can be the scratch itself???
        StorageService *src = std::get<1>(file_copy);
        if (src == ComputeService::SCRATCH) {
          if (this->scratch_space == nullptr) {
            throw WorkflowExecutionException(std::shared_ptr<FailureCause>(new NoScratchSpace("WorkunitMulticoreExecutor::performWork(): Scratch Space was asked to be used as source but is null")));
          }
          src = this->scratch_space;
        }
        StorageService *dst = std::get<2>(file_copy);
        if (dst == ComputeService::SCRATCH) {
          if (this->scratch_space == nullptr) {
            throw WorkflowExecutionException(std::shared_ptr<FailureCause>(new NoScratchSpace("WorkunitMulticoreExecutor::performWork(): Scratch Space was asked to be used as destination but is null")));
          } else {
            dst = this->scratch_space;
          }
        }

        if ((file == nullptr) || (src == nullptr) || (dst == nullptr)) {
          throw std::runtime_error("WorkunitMulticoreExecutor::performWork(): internal error: malformed workunit");
        }

        try {
          WRENCH_INFO("Copying file %s from %s to %s",
                      file->getID().c_str(),
                      src->getName().c_str(),
                      dst->getName().c_str());

          S4U_Simulation::sleep(this->thread_startup_overhead);
          dst->copyFile(file, src);
        } catch (WorkflowExecutionException &e) {
          throw;
        }

        if (dst == this->scratch_space) {
          files_stored_in_scratch.insert(file);
        }
      }try {
            StorageService::writeFiles(task->getOutputFiles(), work->file_locations, this->scratch_space,
                                       files_stored_in_scratch);
        } catch (WorkflowExecutionException &e) {
          task->setInternalState(WorkflowTask::InternalState::TASK_FAILED);
            this->simulation->getOutput().addTimestamp<SimulationTimestampTaskFailure>(new SimulationTimestampTaskFailure(task));
            throw;
        }

        WRENCH_INFO("Setting the internal state of %s to TASK_COMPLETED", task->getID().c_str());
        task->setInternalState(WorkflowTask::InternalState::TASK_COMPLETED);

        // Deal with Children
        for (auto child : task->getWorkflow()->getTaskChildren(task)) {
          bool all_parents_completed = true;
          for (auto parent : child->getWorkflow()->getTaskParents(child)) {
            if (parent->getInternalState() != WorkflowTask::InternalState::TASK_COMPLETED) {
              all_parents_completed = false;
              break;
            }
          }
          if (all_parents_completed) {
            child->setInternalState(WorkflowTask::InternalState::TASK_READY);
          }
        }

        task->setEndDate(S4U_Simulation::getClock());
        task->setExecutionHost(this->hostname);

        // Generate a SimulationTimestampTaskCompletion
        this->simulation->getOutput().addTimestamp<SimulationTimestampTaskCompletion>(
                new SimulationTimestampTaskCompletion(task));
      }

      WRENCH_INFO("Done with all tasks");


      /** Perform all post file copies operations */
      .
      .
      .
      .
      }
```
Is it best if I keep function calls like `this->simulation->getOutput().addTimestamp<SimulationTimestampTaskXXXX>(
                new SimulationTimestampTaskXXXX(task))` outside of functions like `WorkflowTask::setInternalState()` or `WorkflowTask::setStart/EndDate()`? 

Do we want to keep multiple `SimulationTimestampTaskStart`s and `SimulationTimestampTaskFailure`s for a given task when they occur? That seems useful. As it stands, a new `SimulationTimestampTaskXXXX`  can be created for the same task multiple times and the user is responsible for filtering what they want in the end.

**Comment by rafaelfsilva** [comment]
Hi @ryantanaka, here it is my 2% on that:

I would suggest to move the events creation into functions like `WorkflowTask::setInternalState()` or `WorkflowTask::setStart/EndDate()` since such events are related to the task behavior. Also, it would be transparent in case someone decides to implement a new workunit executor in the future.

I also vote for keeping multiple events for task start and failure, there are several situations when you want to explore the dynamic behavior of the system, and such information is very helpful. For now, let's leave for the user to deal with the events filtering. In the future, we may want to build smart filters for data visualization.

@henricasanova, any additional comments?

**Comment by henricasanova** [comment]
I agree with Rafael.

**Comment by ryantanaka** [comment]
Alright, thank you for the input :)
 I placed the timestamp creation for tasks in `WorkflowTask::setInternalState()`:

```cpp
    /**
     * @brief Set the internal state of the task
     *
     * @param state: the task's internal state
     */
    void WorkflowTask::setInternalState(WorkflowTask::InternalState state) {
        this->internal_state = state;


      //check that the simulation object isn't nullptr (ie check that the workflow was added to the simulation)
        // doing this to avoid breaking tests at the moment. if the workflow isn't added to the simulation, there
        // will be no SimulationTimestampTaskXXXX'
                auto sim = this->workflow->simulation;
        if (this->workflow->simulation != nullptr) {
            switch (state) {
                case TASK_RUNNING:
                    this->workflow->simulation->getOutput().addTimestamp<SimulationTimestampTaskStart>(
                            new SimulationTimestampTaskStart(this));
                    break;

                case TASK_FAILED:
                    this->workflow->simulation->getOutput().addTimestamp<SimulationTimestampTaskFailure>(
                            new SimulationTimestampTaskFailure(this));
                    break;

                case TASK_COMPLETED:
                    this->workflow->simulation->getOutput().addTimestamp<SimulationTimestampTaskCompletion>(
                            new SimulationTimestampTaskCompletion(this));
                    break;
            }
        }
    }
```
and then  exposed `Workflow` to the simulation pointer like this in `Simulation.cpp`:

```cpp
    Workflow *Simulation::add(Workflow *workflow) {
      if (workflow == nullptr) {
        throw std::invalid_argument("Simulation::add(): invalid argument");
      }
      if (not this->s4u_simulation->isInitialized()) {
        throw std::runtime_error("Simulation::add(): Simulation is not initialized");
      }
      workflow->simulation = this;
      return workflow;
    }
```
So, a user will need to `simulation.add(workflow)` if they wan't the workflow tasks to be "traceable". Should I make this a strict requirement?

And does the start and completion timestamp of a task include the initial `StorageService::readFiles()` and `StorageService::writeFiles()`?

Right now when the tasks are executed in https://github.com/wrench-project/wrench/blob/772f87586506e8a3d75a153e9472a99eb94b86ca/src/wrench/services/compute/standard_job_executor/WorkunitMulticoreExecutor.cpp#L222-L223

we have:
1. set internal state RUNNING
2. readFiles
3. set start date
4. runMulticoreComputation
5. writeFiles
6. set internal state COMPLETE
7. tell all child tasks whether they can switch to READY
8. set end date

Was the setStartDate meant to be before the readFiles since setEndDate comes after writeFiles?

**Comment by henricasanova** [comment]
1) About the simulation.add(workflow). I think that, since the user will do a wms.addWorkflow(), perhaps in there we can call simulation.add(workflow) so that the user never has to do it. And that way, all workflows are tracable? 

2) about the "when does a task start", yes, it's a bit incoherent.  After all, the readFiles() and writeFiles() are part of the task's process. Ideally, we'd simulate a task as a sequence of I/O and compute operations, while here we says "do all your input, then all your computation, then all your output".  So, I am thinking we should move the "set start date" before the "readFiles" and reading input files is part of the task execution.  Later we could actually have sub-events:  read_input_start, read_input_end, compute_start, compute_end, write_output_start, write_output_end...

**Comment by ryantanaka** [comment]
> About the simulation.add(workflow). I think that, since the user will do a wms.addWorkflow(), perhaps in there we can call simulation.add(workflow) so that the user never has to do it. And that way, all workflows are tracable?

Alright, that's a better Idea. I made that change, but ended up not making the `simulation.add(workflow)` function.

```cpp
    void WMS::addWorkflow(Workflow *workflow, double start_time) {


      if ((workflow == nullptr) || (start_time < 0.0)) {
        throw std::invalid_argument("WMS::addWorkflow(): Invalid arguments");
      }


      if (this->workflow) {
        throw std::invalid_argument("WMS::addWorkflow(): The WMS has already been given a workflow");
      } else {
        this->workflow = workflow;


        /**
         * Set the simulation pointer member variable of the workflow so that the
         * workflow tasks have access to it for creating SimulationTimestamps
         */
        this->workflow->simulation = this->simulation;
      }
      this->start_time = start_time;
    }
```

> about the "when does a task start", yes, it's a bit incoherent. After all, the readFiles() and writeFiles() are part of the task's process. Ideally, we'd simulate a task as a sequence of I/O and compute operations, while here we says "do all your input, then all your computation, then all your output". So, I am thinking we should move the "set start date" before the "readFiles" and reading input files is part of the task execution. Later we could actually have sub-events: read_input_start, read_input_end, compute_start, compute_end, write_output_start, write_output_end...

ok thanks for the clarification. this change has been made and I wrote some tests for SimulationTimstampTaskXXXX. I edited your initial comment in this issue mentioning the sub-events.

**Comment by ryantanaka** [comment]
@henricasanova @rafaelfsilva 

Hi all, I was wondering if you might have some input on this. So our current implementation of the `SimulationOutput::getTrace()` and the `SimulationTimestampXXXX` requires some tedious checking  to match start times to end/failure times. As I was making a gantt chart for the pedagogic modules, I thought it might be useful if this was already done in the code. @mesurajpandey and I thought maybe having a `event_id` created whenever some SimulationTimestampXXXXStart is created (see below), which can then be passed into the SimulationTimestampXXXXCompletion constructor when that event is complete or fails. 

```cpp
namespace wrench {

    class WorkflowTask;
    class WorkflowFile;
    class StorageService;

    class SimulationTimestampEventType {
    public:
        SimulationTimestampEventType() {

        }

        SimulationTimestampEventType(unsigned long event_id) : event_id(event_id) {

        }

        unsigned long getEventID() {
            return this->event_id;
        }

    protected:
        unsigned long event_id;

    };

    class SimulationTimestampEventStart : public SimulationTimestampEventType {

    public:
        SimulationTimestampEventStart() {
            this->event_id = next_event_id++;
        }


    private:
        static unsigned long next_event_id;

    };

    unsigned long SimulationTimestampEventStart::next_event_id = 0;

    /**
    * @brief A base class for simulation timestamps regarding workflow tasks
    */
    class SimulationTimestampTask {

    public:

        /***********************/
        /** \cond DEVELOPER    */
        /***********************/

        /**
         * @brief Constructor
         * @param task: a workflow task
         */
        SimulationTimestampTask(WorkflowTask *task) {
            this->task = task;
        }

        ~SimulationTimestampTask() {

        }

        /***********************/
        /** \endcond           */
        /***********************/

        /**
         * @brief Retrieve the task that has completed
         *
         * @return the task
         */
        WorkflowTask *getTask() {
          return this->task;
        }


    private:
        WorkflowTask *task;
    };

    class SimulationTimestampTaskStart :public SimulationTimestampEventStart, public SimulationTimestampTask {
    public:
        SimulationTimestampTaskStart(WorkflowTask *task) : SimulationTimestampTask(task) {

        }
    };

    class SimulationTimestampTaskFailure : public SimulationTimestampEventType, public SimulationTimestampTask {
    public:
        SimulationTimestampTaskFailure(WorkflowTask *task, unsigned long event_id) : SimulationTimestampEventType(event_id), SimulationTimestampTask(task) {

        }
    };

    class SimulationTimestampTaskCompletion : public SimulationTimestampEventType, public SimulationTimestampTask {
    public:
        SimulationTimestampTaskCompletion(WorkflowTask *task, unsigned long event_id) : SimulationTimestampEventType(event_id), SimulationTimestampTask(task) {

        }
    };

    /**
     * @brief A base class for simulation timestamps regarding file copies
     */
    class SimulationTimestampFileCopy {
    public:
        SimulationTimestampFileCopy(WorkflowFile *file, StorageService *source, std::string source_partition,
                                    StorageService *destination, std::string destination_partition) :
                                    file(file), source(source), source_partition(source_partition), destination(destination),
                                    destination_partition(destination_partition) {

        }

        WorkflowFile *file;

        StorageService *source;
        std::string source_partition;

        StorageService *destination;
        std::string destination_partition;
    };

    class SimulationTimestampFileCopyStart : public SimulationTimestampEventStart, public SimulationTimestampFileCopy {
    public:
        SimulationTimestampFileCopyStart(WorkflowFile *file, StorageService *source, std::string source_partition,
                                         StorageService *destination, std::string destination_partition) :
                SimulationTimestampFileCopy(file, source, source_partition, destination, destination_partition) {

        }
    };

    class SimulationTimestampFileCopyCompletion : public SimulationTimestampEventType, public SimulationTimestampFileCopy {
    public:
        SimulationTimestampFileCopyCompletion(WorkflowFile *file, StorageService *source, std::string source_partition,
                                         StorageService *destination, std::string destination_partition, unsigned long event_id) :
                SimulationTimestampFileCopy(file, source, source_partition, destination, destination_partition), SimulationTimestampEventType(event_id) {

        }
    };

    class SimulationTimestampFileCopyFailure : public SimulationTimestampEventType, public SimulationTimestampFileCopy {
    public:
        SimulationTimestampFileCopyFailure(WorkflowFile *file, StorageService *source, std::string source_partition,
                                         StorageService *destination, std::string destination_partition, unsigned long event_id) :
                SimulationTimestampFileCopy(file, source, source_partition, destination, destination_partition), SimulationTimestampEventType(event_id) {

        }
    };

};
```

**Comment by henricasanova** [comment]
The idea of a way to easily link a "start" event to the "done" or "failed" even is great, since indeed otherwise it's really painful.  What you suggest above is ok, but is an "id" the best way to do it? I mean, how to you search for an event with a particular id? Wouldn't it be more natural to pass some "start event" parameter that's simply a pointer to the corresponding start event? Then you'd have a direct pointer to that event... and in that way events could be linked arbitrarily.  Not sure...

**Comment by ryantanaka** [comment]
Alright, I agree that using a pointer to some starting event makes it much easier to link events together. With the "id" thing, a naive type of loop through start/end traces would be needed to match traces by "id". I'm going to implement this using pointers instead.

**Comment by rafaelfsilva** [comment]
Sorry for the delay in joining this discussion. I went through the whole thread and I agree with all decisions. Thank you!

**Comment by ryantanaka** [comment]
Hi all, 
I've implemented Task start, Task failure, File copy begins, File copy end, and File copy failure SimulationTimestamps with some tests. In summary, task timestamps are set in `WorkflowTask::setInternalState()` as was suggested above. For file copy timestamps, a `SimulationTimestampFileCopyStart` is created right before a `StorageServiceFileCopyRequestMessage` is sent. A `SimulationTimestampFileCopyCompletion` is created right after the file has been inserted into the destination storage service. A `SimulationTimestampFileCopyFailure` is created if a `StorageServiceFileCopyAnswerMessage` is sent due to a failure. All timestamps have a function to get its corresponding start or failure/completion timestamp. 

Can you guys take a look at the code? If the implementation looks okay, should I go ahead and work on 

read_input_start
read_input_end
compute_start
compute_end
write_output_start
write_output_end

thank you!

**Comment by henricasanova** [comment]
Hi Ryan,

this looks good to me. At first I was wondering why you'd set the SimulationTimestampFileCopyCompletion event before the ack is sent (noting that the ack may or may not be set).  But then, sending the ack is a putMessage(), which is synchronous.... so you opted to set the event when the file is sent since after all the putMessage() could be stuck there a while due to synchronicity.  At some point I thought all acks should be dputMessage()... not sure why I left them synchronous.  So, any way, the only thought I have is that a perhaps more coherent view is:

client side:
  set start event
  send request message

server side:
  send (asynchronous) answer message
  set end event

this way, both "send message" operations are part of the timed operation, not just one.  This is a tiny detail.... and it's fine as it is though.   If you have any thoughts let me know.

The rest all looks great.

**Comment by ryantanaka** [comment]
Thank you for looking over this. I agree with this being more coherent by including the 'ack send' time. Right now, `StorageServiceFileCopyRequestMessage`s are only sent from a client with `putMessage` and could get stuck for a while as well, so it makes sense that I set the end event after the `ack` to be consistent. 

If, however we do change the `ack` to a `dputMessage`, then it won't matter if we put the `set end event` before or after the `dputMessage` right?

**Comment by henricasanova** [comment]
Yes, if we do dputMessage, it doesn't matter, but from a consistency perspective it's more logical to put the event after the dputMessage. 

And thinking about it, I believe we should make all "a service sends back a reply" message sends asynchronous. So for now, just make that one a dputMessage.

**Comment by ryantanaka** [comment]
Okay got it, I've made that change and this is done now. I'll submit a PR.
