### ISSUE TITLE
Feature Request: a "Virtualized Cluster" compute service

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#15]
- A visible physical infrastructure
- The ability to create/migrate/kill VM by hands
- Each VM would expose a MHMVCS as in the cloud

**Comment by rafaelfsilva** [comment]
Link to S4U VM migration example: https://github.com/simgrid/simgrid/blob/master/examples/s4u/cloud-migration/s4u-cloud-migration.cpp
