### ISSUE TITLE
Enhancements to  Simulation Timestamps and JSON output

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#154]
- [x]  Add the file name to the "read" element of the JSON output (since  the corresponding TimeStamp has the file)
- [x]  Add a DiskReadStart/End and DiskWriteStart/End TimeStamp, and generate them in S4U_Simulation.cpp (see "TODO" comments therein)
- [x] Add a  "disks" section to the JSON with data  from the above timestamp (num  bytes, host, disk path)
- [x] Enhance the SimulationOutput API so that one must enable various "categories" of  time-stamps.
- [x] Make sure Doxygen document for all the "dump JSON" methods is up-to-date

**Comment by willkoch** [comment]
File IDs added to read/write

**Comment by henricasanova** [comment]
Modified  the API so that timestamp constructors are now private, and instead a number of addTimestamp...() methods have been added to SimulationOutput. After tinkering with heavily templated complicated design, went for simple.   

New methods added  to enable/disable timestamp generation at the user-level. By default, all currently available timestamps are enabled, but likely the  upcoming disk-related timestamps will not. Look in the constructor SimulationOutput::SimulationOutput() where the default enabled/disabled statuses are set.

**Comment by willkoch** [comment]
Timestamps implemented (with wrapper in Simulation.cpp instead of S4U_Simulation.cpp) and JSON added for disk specific output. Disk timestamps disabled by default

**Comment by willkoch** [comment]
Fixed formatting for all dumps. Closing now, not yet reflected on the website.
