### ISSUE TITLE
Documentation redundancy: WRENCH  101 / Guide

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#156]
After adding some words to  the WRENCH Guide, there is  quite a bit of redundancy between WRENCH 101 and the Guide. For some things one it more specific, for others the other is more specific. I am thinking that we should just put everything under 101....

**Comment by rafaelfsilva** [comment]
@henricasanova, I agree with you, since we like making pedagogic modules, maybe we could split it into WRENCH 101, 102, 201, etc. What do you think?

**Comment by henricasanova** [comment]
For now, I am thinking of all in  101 with links  to "internal" documents  with some of the more detailed "guide" information.  In the process of doing that, I may create a 102. . Also, I am thinking of adding a few more examples to the examples directory.   I'll take a first stab at all this, and we'll see what we think.

**Comment by rafaelfsilva** [comment]
Sounds great to me!

**Comment by henricasanova** [comment]
I am having  a small issue, and  I am not sure how to resolve it.   As Rafael and I discussed yesterday, we're removing the "user/devel/internal" "button"  as now the documentation text  (i.e., wrench-101, wrench-102) is simply always visible. It was confusing that clicking on the "button" would modify the content.The idea is now just to have a pull-down menu on the API top-level item that allows to select the  level of documentation.

The issue I am having is this, taking wrench-102 as an example. In  wrench-102.md I have something like `wrench::SomeMethod`. Conveniently, this generates a link to the API. But this link is based on the directory I am in. So, if I view the  user documentation,  then  this  link is not inserted if SomeMethod is not in the User API. 

This all makes sense, but I am not sure how  to resolve it.... perhaps it's a bit of a showstopper?   Regardless, I'll continue  writing content for now

**Comment by rafaelfsilva** [comment]
You can keep working like that for now, and I can try to find some magic trick to automatically change the paths during compilation or something else :)

**Comment by henricasanova** [comment]
I  just finished my (super extensive!) pass on  the  documentation. It's all pushed to master, and ready  to somebody  to review. I  didn't touch much  the HTCondor documentation (as I never looked into that), so  Rafael if you want to add/modify it, that's great).

**Comment by rafaelfsilva** [comment]
I have completed a review on WRENCH 101 and 102 pages.

**Comment by henricasanova** [comment]
ok. so perhaps time  to close this issue? Or is there more for us to discuss?

**Comment by rafaelfsilva** [comment]
I think it can be closed.
