### ISSUE TITLE
Stop using the Lemon library?

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#159]
Since the beginning, we've used the Lemon library for dealing with the DAG underlying the workflow. An alternative was the boost graph library, which the first student working on the project found too heavy-duty. But looking at examples, I think it could be straightforward to switch over the boost library. And since we already require boost, that would simply  remove a dependency. Furthermore, lemon is a bit dead.   Henri will likely be exploring this in a branch, perhaps even before the next release!

**Comment by rafaelfsilva** [comment]
That would be great!

**Comment by henricasanova** [comment]
I just pushed a fix to the master  where lemon is no longer in the picture! I tested/valgrinded  it on linux/MacOS. The boost GL  isn't super easy to use, and the current implementation can likely be a bit improved (in terms of style).

**If this works, we should remove lemon from all Docker instances!**

**Comment by rafaelfsilva** [comment]
Lemon has been removed from all Docker instances. I think we can close this issue.
