### ISSUE TITLE
Dashboard Host Utilization  graph display bug

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#164]
When using the  attached  JSON output  file, the dashboard's Host utilization  graph looks strange, with the x axis too low,  and strange overlap  of tasks...

[example_output.json.txt](https://github.com/wrench-project/wrench/files/4589569/example_output.json.txt)

**Comment by rafaelfsilva** [comment]
Strange, I will investigate it. Most probably due to the recent changes I did.
