### ISSUE TITLE
Mutiple namespaces?

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#17]
It may be a good idea to have a namespace for "user" and a namespace for "developer".

**Comment by rafaelfsilva** [comment]
It sounds an interesting idea, but I am not aware of a way to have two different namespaces calling the same function. For example, consider we have a function `add()` that would be available for the user and also the developer, and a function `remove()` that is only available to the developer, which is declared as follows:

```
namespace wrench {
   void add() {}
}

namespace wrenchdev {
  void remove() {}
}
```

In such case, the user will invoke `add()` via `wrench::add()` (only one namespace to manage), however the developer would have to manage two namespaces, one to call `wrench::add()` and another to call `wrenchdev::remove()`. Ideally, I would like to have something as:

- for the _user_: `wrench::add()`
- for the _developer_: `wrenchdev::add()` and `wrenchdev::remove()`

But I am not aware of mechanisms to enable such capability. @henricasanova , do you have anything else in mind?

**Comment by henricasanova** [comment]
Hi,

so this is actually Fred Suter’s idea, so I won’t take responsibility.  But what I saw was something like this to “merge” namespaces.

https://stackoverflow.com/questions/7170214/possible-to-wrap-or-merge-separate-namespaces

(look at the 1st answer). In C++17 it seem we could do:

namespace wrench {

  void add() {}

namespace wrench-dev {
  void remove{};
}
}

namespace wrenchdev {
  using namespace wrench;
  using namespace wrench::wrench-dev;
}


Note that I have absolutely never tried this at all, but it might be worth checking it out.

cheers
Henri

**Comment by rafaelfsilva** [comment]
An alternative approach would be to use sub-namespaces:

```
namespace wrench {
  void someMethod();

  namespace dev {
     void devMethod();
  }
}
```

Then the users would invoke the functions using `wrench::someMethod()` and `wrench::dev::devMethod()`.

What do you think?

**Comment by henricasanova** [comment]
> On Feb 26, 2018, at 1:47 PM, Rafael Ferreira da Silva <notifications@github.com> wrote:
> 
> An alternative approach would be to use sub-namespaces:
> 
> namespace wrench {
>   void someMethod();
> 
>   namespace dev {
>      void devMethod();
>   }
> }
> Then the users would invoke the functions using wrench::someMethod() and wrench::dev::devMethod().
> 
> What do you think?
> 
I like it. 

Henri

**Comment by rafaelfsilva** [comment]
As life is not perfect, my proposed approach is not valid (see the answers for this post: https://stackoverflow.com/questions/13484387/why-cant-we-declare-a-namespace-within-a-class). Thus, multiple namespaces would be viable if we had different classes for different user types.

One possible way is to declare classes with private constructors to represent the dev namespace, however I find it quite a hacky way.

Any new insights?

**Comment by henricasanova** [comment]
Hi WRENCH-ers,

I though I would send this e-mail to keep you appraised of changes to the design and implementation that I am currently experimenting with in a branch. I’l keep this as short as possible:

* Motivation for changes:
	- To solve the “who should shutdown services when?”  issue, we made most services “daemonized” (i.e., SimGrid won’t complains if they’re still running at the end of the simulation)
	- By making most running S4U processes daemonize we created an issue with the Batsched integration
 	- Suraj and I worked on that issue and solved it one way
	- That way then caused weird bugs in other services
	- And after investigating these bugs it’s _again_ the same difficult issue: a service object may be destroyed while the service’s simulator process (the SimGrid actor) is still running
	- This issue has been bothering me for months and months, and has been a source of ugly bugs forever

Suraj and I came up with a way to redesign the internals in a ways that solves that design issue.  It works (just finished implementing/testing in my branch). But if has, interestingly, implications on the top-level APIS:

	For users:
		- No more std::unique_ptr in user space  (this is actually something Fred had complained about, so I view it as a bonus!)
	For developers:
		- Forced to use some factories instead of calling constructors directly (this is, in my mind, a better thing as well)
	For internals:
		- Some low-level insanity, confined two two small classes, so no big deal 
		- Need to implemented the above factories



So, in my mind, this is all 100% positive and great. My plan is to keep working on this for 2-3 days, and then merge.  It will break Fred and James simulators, but should be super easy to fix.  

Let me know if you have any concerns.  One option is to hold off, for me to keep going with this, and then discuss it at length during our conf call next week.

cheers
henri

**Comment by henricasanova** [comment]
Hi WRENCH people,

you probably have seen many commit messages from me lately. I am making a full pass through our documentation, and in the process discovering inconsistencies, weirdnesses, etc.   I am thus fixing not only the documentation but many aspects of the API (I just saw an e-mail from Rafael saying he’s updated his Pegasus simulator accordingly).  If you’re working in your own branches, doing a “git merge master” is probably a good idea.   I should be done today and given what’s missing I don’t expect a lot of changes, but that’s what I’ve been telling myself all week :)

cheers
Henri

**Comment by henricasanova** [comment]
This is not going to happen in any foreseeable future, so I am closing this for now.
