### ISSUE TITLE
Dashboard's Host (and Disk) Utilization graph: time range

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#171]
It would be very useful to have the host-utilization (which should really become a host+disk utilization) graph drawing function to make  it possible to specify an optional time range. This is so that one can zoom into a particular region of the execution.  Perhaps it would be even useful to be able to specify multiple ranges, so that one can show particular sections of the timeline, with, e.g., "..." in between these sections in the graphical display? This may be overkill though

**Comment by gjethwani** [comment]
So after I make it host + disk utilization, you would want me to make
functionality to zoom into a particular time range? Would you like this for
all graphs?

**Comment by rafaelfsilva** [comment]
@gjethwani, if you have the time it would be great. If not, I can work on it once you are done with the graph. Thanks

**Comment by henricasanova** [comment]
If we can do that for all graphs of course that's great, but I think it's highest priority for the resource utilization graph.

**Comment by rafaelfsilva** [comment]
@henricasanova I have just added the zoom capability to the charts. Let me know if this solves this issue, so I can close it.

**Comment by henricasanova** [comment]
The zoom is great, and I think we can close the issue for now. In the future, perhaps we will want to just not show the beginning of the simulation. For instance, for the CI stuff, perhaps we don't want to show the beginning of the simulation while the network proximity service warms up?  But perhaps, this can be done at the C++ level, with the "dump to JSON" function specifying a time range?  But for now, we can definitely live without this, so I vote we close the issue :)

**Comment by rafaelfsilva** [comment]
Cool. I believe it would be possible to also limit the values in the chart. Let's look into that once we have the CI modules in better shape. I am closing this issue for now.
