### ISSUE TITLE
Doxygen optional?

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#172]
A user just mentioned that although the documentation says that Doxygen is optional for WRENCH, in fact it's needed....  we should double-check that at some point.

**Comment by rafaelfsilva** [comment]
In fact, the `CMakeLists.txt` is fine, but I think the user got confused with the warning message. I have updated the error message:
```
-- Doxygen: No (warning: Doxygen is needed in case you want to generate WRENCH documentation)
```
