### ISSUE TITLE
Dashboard: custom legend labels

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#173]
This is something that we discussed with Gautam, but I figured if we make it into an issue then we won't forget. 

The idea is to enhance the dashboard graph functions so that an (optional) argument can be passed to customize the caption labels. For instance, in the task execution graph, it says "reading input", but sometimes we really want this to say "receiving input". Or sometimes, we don't want to see anything.For instance, it's weird to see the "reading input" and "writing output" caption items in a (pedagogic) simulation in which there is no input or output. 

Also, it would be good for the "task data" table to specify which columns to show, for the same reason as above.

**Comment by rafaelfsilva** [comment]
The `generateGanttChart` and `populateWorkflowTaskDataTable` functions have now a `label` parameter that can be parameterized as follows:

```javascript
{
    read: {display: true, label: "Reading Input"},
    compute: {display: true, label: "Performing Computation"},
    write: {display: true, label: "Writing Output"},
}
```
