### ISSUE TITLE
Feature Request:"copy and register", "delete and unregister" abilities

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#18]
It would be good to augment the DataMovementManager and other components (e.g., job executors perhaps) with the option to do a combined "create/copy a file AND add an entry in the FileRegistryService". Similarly, when removing a file from a storage Service, it would be good to have a "remove and unregister".  The objective is for a WMS developer who wants everything to be registered to not have to do tons of explicit separate register/unregister operations.

First step:
 

- Modify the StorageService::deleteFile() API to take in a FileRegistryService pointer. It not nullptr is passed, then update the file registry service ONLY if the delete operation is successful
- Modify the DataMovementManager (synchronous and asynchronous) to take in a FileRegistryService pointer. It not nullptr is passed, then update the file registry service ONLY if the copy operation is successful. 
     - This will require adding a "pending file copies" data structure to the DataMovementManager
     -  Algorithm is:
         - For each file copy request keep track of "update file registry service" or "don't update" 
         - When receiving a "file copy done or failed" message: 
             - If not failed: (i) check whether file registry service should be updated; (ii) if yes, update it.

**Comment by ryantanaka** [comment]
@ryantanaka test if everything checks out

**Comment by ryantanaka** [comment]
These have been implemented with tests. Closing.
