### ISSUE TITLE
Add a way to get a network link's usage during the simulation

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#182]
This feature could be useful for the dashboard or for pedagogic activities in which we'd like to display network traffic, perhaps integrating it into the JSON upon request by the user

- [x] Implement necessary methods in Simulation.cpp
- [x] Implement relevant SimulationOutput Timestamp stuff
- [x] Implement a BandwidthMeterService (just like power-meter, starts on whatever hosts, and is given a link to monitor)
- [x] Augment the JSON scheme
- [x] Add the "save to JSON" stuff (which is disabled by default)

**Comment by henricasanova** [comment]
Turns out SimGrid now provides all that we need to get link bandwidth usage. So that is now part of the Simulation class's API.

**Comment by willkoch** [comment]
Timestamp and functions added in branch, only thing remaining is to create the json output.

**Comment by willkoch** [comment]
Feature completed in branch.
