### ISSUE TITLE
Automatic build on framagit broken

### ISSUE THREAD

**Issue by mquinson** [wrench-project/wrench#203]
Hello friends, 

framagit broke again : https://framagit.org/simgrid/external-projects-ci/-/jobs/1091471

I'm not sure of whether reporting this as a bug here is the way you prefer. Please tell me how to I should report it if you prefer otherwise.

Bye, Mt

**Comment by henricasanova** [comment]
Reporting it this way is fine. Looks like https://github.com/nlohmann/json/archive/v3.7.0.tar.gz no longer compiles on that VM/docker.  It compiles fine on Bionic. Let me investigate....

**Comment by rafaelfsilva** [comment]
which OS are you using to build wrench?

**Comment by henricasanova** [comment]
This was due to nlohmann/json being too old. Upgraded external-projects-ci/wrench/wrench.sh to use version 9.0.1 instead, and was able to build everything locally in the simgrid/unstable docker. Closing this.
