### ISSUE TITLE
SimpleStorageService:  num_connections as constructor argument or property?

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#22]
Should the number of concurrent connection be a constructor argument (as it is now) or just an optional property (default being: unlimited).  Although I implemented the former, I now think the latter is better.

**Comment by rafaelfsilva** [comment]
I tend to agree with the optional property approach. Most of users will not set this property, but it is always good to provide ways to configure it.

**Comment by henricasanova** [comment]
done.
