### ISSUE TITLE
Add a min_cores and max_cores argument to loadWorkflowFromJSON and loadWorkflowFromDAX methods

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#223]
Right now, 1 is harcoded for both value. Would be useful to allow users to specify what they want it 1 is not to their liking. 

@rafaelfsilva  do you think that's ok?

**Comment by rafaelfsilva** [comment]
Currently in the JSON schema (https://github.com/wfcommons/workflow-schema) there is a field called `cores` that specifies the number of cores required by the task (although typically not much used). Would that be enough, our should we expand the schema to support min and max?

**Comment by henricasanova** [comment]
Having a single value is ok perhaps, but then one may want to simulate different number of cores.  I guess the issue then will be that if the JSON file doesn't specify it, or say has it as "1", then there is no way to change it. That is, there is no WorkflowTask::setMinNumCore or setMaxNumCore.

**Comment by henricasanova** [comment]
By the way, if the JSON contains a specified number of cores, then I'll enforce that that value is used.

**Comment by rafaelfsilva** [comment]
sounds good to me. thanks!
