### ISSUE TITLE
Problem with Workflow::loadFromJSON on Mac?

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#24]
I haven't had time to look into it, but one of our users has written a small simulator, and the loadFromJSON works on Linux, but not on Mac. I am attaching here the JSON file that causes problems. (had to rename is .json.txt so that Github would allow me to attach)
[E1S51u.json.txt](https://github.com/wrench-project/wrench/files/1816679/E1S51u.json.txt)

**Comment by frs69wq** [comment]
Here is an updated version of this example JSON file that is compliant with the recent modifications of the parser: [E1S51u.json.txt](https://github.com/wrench-project/wrench/files/1851042/E1S51u.json.txt)
I don't know if the issue on Mac is still here though.

**Comment by james-oeth** [comment]
I am getting a invalid json file exception on mac as well let me try to look into it more.

**Comment by james-oeth** [comment]
It works with the new file that Federic sent in on my mac.

**Comment by rafaelfsilva** [comment]
I have updated the parser last week (commit: 2092446f20e3ef37ea849dec35c079bf3d8cf91f), not sure if this fixed the problem.
