### ISSUE TITLE
Improved and additional documentation

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#248]
- [x] Make it so that links to the documentation pieces are something like ".../.../latest/../../" so that people don't have to update their bookmarks/links
  - [x] Investigate whether there is an option to have a full Method list in the API documentation (or a way to search for a method)
  - [x] Add a WRENCH "100" about what's a simulation (hosts, processes, services, messages, controller)

**Comment by rafaelfsilva** [comment]
a search feature has been added to the documentation

**Comment by rafaelfsilva** [comment]
`../latest/..` has also been added: https://wrench-project.org/wrench/latest/

**Comment by rafaelfsilva** [comment]
Documentation is now generated using Sphinx
