### ISSUE TITLE
Incorrect parsing of WfFormat

### ISSUE THREAD

**Issue by osukhoroslov** [wrench-project/wrench#262]
**WRENCH Information**
- WRENCH version: master branch
- CMake version: NA
- Compiler name and version: NA

**Describe the bug**

WfFormat parser in WRENCH [assumes](https://github.com/wrench-project/wrench/blob/b0b6eaff025550e513ba5afdab18a0ef2573c2fd/tools/wfcommons/src/WfCommonsWorkflowParser.cpp#L84) that machine speed is in GHz, while according to [format spec](https://github.com/wfcommons/wfformat#machines-property) it is in MHz. See also speed in [example file](https://github.com/wrench-project/wrench/blob/master/examples/workflow_api/real-workflow-example/1000genome-chameleon-2ch-100k-001.json), which is clearly not in GHz. Therefore [this computation of task flops](https://github.com/wrench-project/wrench/blob/b0b6eaff025550e513ba5afdab18a0ef2573c2fd/tools/wfcommons/src/WfCommonsWorkflowParser.cpp#L143) is incorrect by 10^3.

**Comment by henricasanova** [comment]
thanks for noticing this buggy behavior and providing such a clear description of it. This was just fixed on the master branch.
