### ISSUE TITLE
Desired Development: Implement Vivaldi as a Network Proximity Service

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#3]
It would be nice at some point to implement the Vivaldi system as a Network Proximity Service so that it can be used out of the box by WRENCH developers.

**Comment by ryantanaka** [comment]
@henricasanova ,  this is a draft of what i came up with following the intuition we went over on Wednesday (i think it's a little different though). Is something like this okay? 

And also, do I allow the Network Proximity Service to tell a network daemon to talk to itself? It looks like that is currently the case, but I can adjust a few things around for Vivaldi and AllToAll so that it doesn't happen.

```
// need #include <ctime>
                                        // could just pass in the sender mailbox name 
NetworkProximityDaemon * pickCommunicationPeer(NetworkProximityDaemon * sender) {
  std::string network_service_type  = this->getPropertyValueAsString(
                                            "NETWORK_PROXIMITY_SERVICE_TYPE");

  // will hash this since it is unique to daemon
  std:: string sender_mailbox = sender->mailbox_name;

  NetworkProximityDaemon * chosen_peer;
  if (boost::iequals(network_service_type, "alltoall")) {
    // TODO add alltoall stuff
  }
  else { 
    double coverage = this->getPropertyValueAsDouble("NETWORK_DAEMON_COMMUNICATION_COVERAGE");
    int max_pool_size = this->network_daemons.size(); 
    int pool_size = std::ceil(coverage * max_pool_size);

    std::hash<std::string> hash_func;
    std::default_random_engine sender_rng, master_rng;
    std::uniform_int_distribution<unsigned> s_udist, m_udist(0, pool_size - 1); 

    master_rng.seed(time(0));
    sender_rng.seed(hash_func(sender_mailbox));

    int pool_current_index = 0;
    int pool_target_peer_index = m_udist(master_rng);  

    for (int i = 0; i < max_pool_size; ++i) {
      if (s_udist(sender_rng) % (max_pool_size - i) < communication_pool_size) {
        if (pool_target_peer_index = pool_current_index) {
          chosen_peer = this->network_daemons.at(i);
          break;
        }  
        ++pool_current_index;
        --communication_pool_size;
      }   
    }   
  }

  return chosen_peer;
}

```

**Comment by henricasanova** [comment]
> On Feb 12, 2018, at 4:09 PM, Ryan <notifications@github.com> wrote:
> 
> @henricasanova <https://github.com/henricasanova> , this is a draft of what i came up with following the intuition we went over on Wednesday (i think it's a little different though). Is something like this okay?
> 
I think it’s fine but I had something even simpler in mind. (see below)


> And also, do I allow the Network Proximity Service to tell a network daemon to talk to itself? It looks like that is currently the case, but I can adjust a few things around for Vivaldi and AllToAll so that it doesn't happen.
> 
Yeah, let’s not have a daemon talk to itself. And if then user asks for latency(x,x) then we just return 0.  Because the way things are the “talking to oneself” is weird because the daemons are single-threaded…


> // need #include <ctime>
>                                         // could just pass in the sender mailbox name 
> NetworkProximityDaemon * pickCommunicationPeer(NetworkProximityDaemon * sender) {
>   std::string network_service_type  = this->getPropertyValueAsString(
>                                             "NETWORK_PROXIMITY_SERVICE_TYPE");
> 
>   // will hash this since it is unique to daemon
>   std:: string sender_mailbox = sender->mailbox_name;
> 
>   NetworkProximityDaemon * chosen_peer;
>   if (boost::iequals(network_service_type, "alltoall")) {
>     // TODO add alltoall stuff
>   }
>   else { 
>     double coverage = this->getPropertyValueAsDouble("NETWORK_DAEMON_COMMUNICATION_COVERAGE");
>     int max_pool_size = this->network_daemons.size(); 
>     int pool_size = std::ceil(coverage * max_pool_size);
> 
>     std::hash<std::string> hash_func;
>     std::default_random_engine sender_rng, master_rng;
>     std::uniform_int_distribution<unsigned> s_udist, m_udist(0, pool_size - 1); 
>     master_rng.seed(time(0));
This seeding above for master_rng has to happen outside of this function, otherwise pool_target_peer_index below will always be the same! So master_rng needs to be a class variable, not a local variable inside this method.

>     sender_rng.seed(hash_func(sender_mailbox));
This is fine since each time we seed the sender_rng in the same way each time we call this function

> 
>     int pool_current_index = 0;
Up to here, that’s exactly what I had in mind.



>     int pool_target_peer_index = m_udist(master_rng);  
>     for (int i = 0; i < max_pool_size; ++i) {
>       if (s_udist(sender_rng) % (max_pool_size - i) < communication_pool_size) {
>         if (pool_target_peer_index = pool_current_index) {
>           chosen_peer = this->network_daemons.at(i);
>           break;
>         }  
>         ++pool_current_index;
>         --communication_pool_size;
>       }   
>     }   
The above seems almost too fancy. What I had in mind was much simpler, like:

	int num_iterations = s_udist(master_rng) % pool_size;  // Get the number of peers to iterate through (i.e., we’ll pick the num_iterations-th peer in the random sequence of peer indices)
	int peer_index = 0;
	for (int i=0; i < num_iterations; i++) {	// Just go through the random sequence of peer indices, which is always the same because we re-seed sender_rng each time
		peer_index = s_udist(sender_rng) % max_pool_size;  // Take the mod with max_pool_size since we need a valid index
        }
	chosen_peer = this->network_daemons.at(i);  // Pick the peer we stopped at, and we’re done.

makes sense?

Henri

**Comment by ryantanaka** [comment]
> Yeah, let’s not have a daemon talk to itself. And if then user asks for latency(x,x) then we just return 0.  Because the way things are the “talking to oneself” is weird because the daemons are single-threaded…

Okay got it, I'll make that change.

> This seeding above for master_rng has to happen outside of this function, otherwise pool_target_peer_index below will always be the same! So master_rng needs to be a class variable, not a local variable inside this method.

Got it, that makes sense! I was thinking that `time(0)` in ` master_rng.seed(time(0));` would set the seed to something else on each call, but subsequent calls within the same second would keep `pool_target_peer` the same.

> 	int num_iterations = s_udist(master_rng) % pool_size;  // Get the number of peers to iterate through (i.e., we’ll pick the num_iterations-th peer in the random sequence of peer indices)
	int peer_index = 0;
	for (int i=0; i < num_iterations; i++) {	// Just go through the random sequence of peer indices, which is always the same because we re-seed sender_rng each time
		peer_index = s_udist(sender_rng) % max_pool_size;  // Take the mod with max_pool_size since we need a valid index
        }
	chosen_peer = this->network_daemons.at(i);  // Pick the peer we stopped at, and we’re done.
makes sense?

`chosen_peer = this->network_daemons.at(i); ` would be `chosen_peer = this->network_daemons.at(peer_index); ` right? 

Aside from that, it's crystal clear now. Took me a while to wrap my head around `num_iterations` for some reason but yes I agree that method is simpler. I'm going to implement that.

**Comment by ryantanaka** [comment]
@ryantanaka, add some getters for property values to serve as wrappers around getPropertyValueAsString etc.

**Comment by ryantanaka** [comment]
@ryantanaka 
need to fix vivalidi, test showing wrong values

**Comment by ryantanaka** [comment]
@henricasanova , I can't seem to figure this one out, do you have any suggestions?

I fixed part of the Vivaldi Test. It was failing because I didn't make some changes after we had set this line:
https://github.com/wrench-project/wrench/blob/6a502e3ca46903e16a7dc4accf77c7a26f062e2a/include/wrench/services/network_proximity/NetworkProximityService.h#L44

Now the test looks like this:

```
class VivaldiConvergeWMS : public wrench::WMS {
public:
    VivaldiConvergeWMS(NetworkProximityTest *test,
                       std::set<wrench::ComputeService *> compute_services,
                       std::set<wrench::StorageService *> storage_services,
                       std::set<wrench::NetworkProximityService *> network_proximity_services,
                       std::string hostname) :
            wrench::WMS(nullptr, nullptr, compute_services, storage_services,
                        network_proximity_services, nullptr, hostname, "test") {
        this->test = test;
    }

private:
    NetworkProximityTest *test;

    int main() {
      // Create a job manager
      std::shared_ptr<wrench::JobManager> job_manager = this->createJobManager();

      // Create a data movement manager
      std::shared_ptr<wrench::DataMovementManager> data_movement_manager = this->createDataMovementManager();

      std::pair<std::string, std::string> hosts_to_compute_proximity;
      hosts_to_compute_proximity = std::make_pair("Host3", "Host4");
      
      std::set<wrench::NetworkProximityService *> network_proximity_services = this->getAvailableNetworkProximityServices();

      wrench::NetworkProximityService* alltoall_service;
      wrench::NetworkProximityService* vivaldi_service;

        for (auto  &nps : network_proximity_services) {
            std::string type = nps->getNetworkProximityServiceType();

        if (boost::iequals(type, "alltoall")) {
          alltoall_service = nps;
        }

        if (boost::iequals(type, "vivaldi")) {
          vivaldi_service = nps;
        }
      }

      wrench::S4U_Simulation::sleep(100);
      double alltoall_proximity = alltoall_service->query(hosts_to_compute_proximity);
      double vivaldi_proximity = vivaldi_service->query(hosts_to_compute_proximity);

      if (vivaldi_proximity > 1000) {
        throw std::runtime_error("Vivaldi proximity is larger than it should be");
      }

      // Check values
      double epsilon = 0.1 * 1000;

      if (fabs(vivaldi_proximity - alltoall_proximity) > epsilon) {
        throw std::runtime_error("Vivaldi algorithm did not converge");
      }

      std::string target_host = "Host3";
      std::pair<double,double> coordinates = vivaldi_service->getCoordinate(target_host);
      
      if (coordinates.first == 0 && coordinates.second == 0) {
        throw std::runtime_error("Vivaldi algorithm did not update the coordinates of host:" + target_host);
      }
      return 0;
    }
};
```
Everything runs nicely up until `std::pair<double,double> coordinates = vivaldi_service->getCoordinate(target_host);`

At that point, line 98 in NetworkProximityService::getCoordinate() (see snippet bellow) throws a  NetworkError and I can't seem to figure out why. When printing info from the exception, this is what I get: `Network error (link failure, or communication peer died) while receiving from mailbox_name network_get_coordinate_entry_86` https://github.com/wrench-project/wrench/blob/6a502e3ca46903e16a7dc4accf77c7a26f062e2a/src/wrench/services/network_proximity/NetworkProximityService.cpp#L74-L109

**Comment by ryantanaka** [comment]
@ryantanaka double check completion and verify to close issue

**Comment by ryantanaka** [comment]
Vivaldi is implemented with tests.
