### ISSUE TITLE
Improve documentation: small artifact in the examples README.md

### ISSUE THREAD

**Issue by fredgrub** [wrench-project/wrench#308]
There is a string of "jjjjjjjjjjjjjjj" in the file `examples/README.md` (exactly in this [position](https://github.com/wrench-project/wrench/tree/master/examples#action-api-simulator-examples:~:text=%27XRootD%27%3A%20A%20simulation%20of%20a%20storage%20system%20that%20resembles%20the%20XRootD%20storage%20system.jjjjjjjjjjjjjjj)). I believe it is an artifact.

**Comment by henricasanova** [comment]
Thanks for reporting this!
