### ISSUE TITLE
Energy consumption simulation

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#37]
We should evolve WRENCH so that it exposes the "energy" functionality in SimGrid

**Comment by rafaelfsilva** [comment]
SimGrid Examples:
https://github.com/simgrid/simgrid/tree/master/examples/s4u/energy-boot
https://github.com/simgrid/simgrid/tree/master/examples/s4u/energy-exec
https://github.com/simgrid/simgrid/tree/master/examples/s4u/energy-link
https://github.com/simgrid/simgrid/tree/master/examples/s4u/energy-vm

Documentation:
http://simgrid.gforge.inria.fr/simgrid/3.19/doc/group__plugin__energy.html
http://simgrid.gforge.inria.fr/tutorials/simgrid-energy-101.pdf (does not use S4U, but contains good material on how energy consumption is measured and can be configured in SimGrid)

**Comment by frs69wq** [comment]
The energy-101 tutorial has to be updated to show the S4U APIs (C++ and C) but for most of the calls, replacing MSG_ by sg_ does the trick. Do not hesitate if you need help implementing that part.

**Comment by frs69wq** [comment]
I updated the tutorial to use the modern API. It should be online now. Hope it helps.

**Comment by rafaelfsilva** [comment]
Many thanks @frs69wq! Suraj and I will be looking into this, and will get back to you if we have questions.

**Comment by rafaelfsilva** [comment]
Pull request has been merged. I will be writing wrappers for the S4U_Simulation functions into wrench::Simulation class

**Comment by rafaelfsilva** [comment]
We will also need to write a documentation on how to setup the energy consumption in the platform file (or at least refer to the SimGrid information if available).

**Comment by henricasanova** [comment]
@rafael: Suraj will add the wrappers for the S4U_Simulation functions into wrench::Simulation class!

**Comment by rafaelfsilva** [comment]
sounds good. Thanks

**Comment by henricasanova** [comment]
As far as I know, it's all good. Testing has been added by suraj, and all is well.
