### ISSUE TITLE
Can't see SimGrid callback for host state changes

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#38]
[Formerly: We should evolve WRENCH so that it handles host failures as dictated by SimGrid availability traces]
What changed to a SimGrid  Bug issue, and copied to a general issue

**Comment by ryantanaka** [comment]
@henricasanova 

We are having trouble using `simgrid::s4u::Host::on_state_change`. This is what we did:

The platform file looks like this:

```cpp
      std::string trace_file_content = "PERIODICITY 10\n"
              " 0 1\n"
              " 5 0";

      FILE *trace_file = fopen(trace_file_path.c_str(), "w");
      fprintf(trace_file, "%s", trace_file_content.c_str());
      fclose(trace_file);

      // Create a four-host 10-core platform file
      std::string xml = "<?xml version='1.0'?>"
              "<!DOCTYPE platform SYSTEM \"http://simgrid.gforge.inria.fr/simgrid/simgrid.dtd\">"
              "<platform version=\"4.1\"> "
              "   <zone id=\"AS0\" routing=\"Full\"> "
                     "<host id=\"Host1\" speed=\"100f, 0f\" pstate=\"0\" state_file=\""+trace_file_name+"\" core=\"1\" >"
                       "<prop id=\"watt_per_state\" value=\"1.0:2.0, 0:0\" />"
                       "<prop id=\"watt_off\" value=\"0\" />"
                       "</host>"

                      "<host id=\"Host2\" speed=\"100f, 0f\" pstate=\"0\" core=\"1\" >"
                       "<prop id=\"watt_per_state\" value=\"1.0:2.0, 0:0\" />"
                       "<prop id=\"watt_off\" value=\"0\" />"
                       "</host>"
              "       <link id=\"1\" bandwidth=\"50000GBps\" latency=\"0us\"/>"
              "       <route src=\"Host1\" dst=\"Host2\"> <link_ctn id=\"1\"/> </route>"
              "   </zone> "
              "</platform>";
```

Defined several functions like this:

```cpp
static void some_function(simgrid::s4u::Host & h) {
    std::cerr << "i am: " << h.get_name() << " some text..."  << std::endl;
}
```

And then set the following before launching the simulation.

```cpp
simgrid::s4u::Host::on_creation.connect(&some_function1);
simgrid::s4u::Host::on_destruction.connect(&some_function2);
simgrid::s4u::Host::on_state_change.connect(&some_function3);
simgrid::s4u::Host::on_speed_change.connect(&some_function4);
```
We only could get output for `on_creation` at the beginning of the simulation and `on_destruction` at the end of the simulation but not from `on_state_change` as expected. If we can't get `on_state_change` to work, one alternative that we looked at is using `simgrid::s4u::Actor::on_destruction`. @mesurajpandey is testing this out now.

**Comment by henricasanova** [comment]
I duplicated the same problem, and it's a bug in SimGrid. The SimGrid guys are on it... stay tuned.

**Comment by henricasanova** [comment]
More news about this. It turns out that the "Actor forget is daemonized" raised by Suraj a while back, and the issue above are due to the same SimGrid bug. The SimGrid guys realized today that several problems are all related to that same bug. It is being worked on, and a bit complicated. More news later.

**Comment by henricasanova** [comment]
This has been fixed in SimGrid's master branch. We're getting closer to being able to deal with failure traces.
