### ISSUE TITLE
General Compute Service API refactoring

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#41]
At the moment, every compute service has two boolean arguments ( "support pilot jobs", "support standard jobs"), a double argument (the scratch space size), and a plist.   Wouldn't it make more sense to have ALL these arguments part of the plist?  (so that a compute service would only have a hostname and list of compute resources argument, and then an optional plist).

**Comment by rafaelfsilva** [comment]
I like this idea, but it means we will be mixing the message payload with other properties, as it is used in the BatchService. If this is ok with you, I am happy to proceed with these changes.

**Comment by henricasanova** [comment]
> On May 27, 2018, at 8:49 AM, Rafael Ferreira da Silva <notifications@github.com> wrote:
> 
> I like this idea, but it means we will be mixing the message payload with other properties, as it is used in the BatchService. If this is ok with you, I am happy to proceed with these changes.
> 
that’s exactly the one reason to perhaps no do this. The “message payload” properties are low-level purely descriptive things, while the other properties are about what the service really does or can do. And so the “important” properties will look a bit lost among the “message payload” properties.   

Here are several options in case we want to move forward with this:

1) do nothing and live with the important properties being lost among the message payload properties

2) separate properties into two classes, and have the service constructors look like:

		Constructor(…, …, functional_properties, message_payload_properties={})

	with the functional_properties above required to be always passed as {} for “use default” (to avoid ambiguous constructors, etc.).  This is sort of clean but perhaps a bit overkill. 

3) A stupid/ugly but easy idea: rename the message property names with, say, a ‘ZZZ_’ in front. That forces them to be listed all together at the end of the property list in the documentation (provided we set the appropriate Doxygen configuration, which I’ve tried and works).  Probably too ugly though, as the “ZZZ” doesn’t mean anything at all :)


Those are all the ideas I have. What do you think? 2) above is likely the cleanest. I am happy to implement it soon if you agree. But if for some reasons you love 3) that’s easy too ;)

Henri

**Comment by rafaelfsilva** [comment]
I like idea 2), and I agree it is cleaner. Let's go with this one. Maybe we do not need to force the `functional_properties` to always be passed – we could set as default `{}`, so if the user does not provide it, we use the default values, as it is for the general `plist`.

**Comment by henricasanova** [comment]
Decided to leave the "scratch space size" argument in the constructor of the compute services rather than have it as property. The rational is that it describes the "hardware resources" used by the service. So the constructor is basically taking 3 required arguments:
  - The host on which the service main daemon runs
  - The list of compute hosts
  - The scratch space size
Everything else is a property because it changes the service's behavior

Onward to splitting properties as discussed above.
