### ISSUE TITLE
Feature Request: Ability to simulate multiple workflows with arrival times

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#5]
At the moment, WRENCH only simulates one workflow execution. Users (e.g., Eddy Caron) have request a much more powerful model in which multiple workflows can arrive dynamically throughout the simulation. This requires some software engineering (and likely some thought).  Furthermore, there should be the possibility of multiple WMS instances running concurrently, OR a single WMS instance managing multiple arriving worflows.

Before we get there we need:

  1. Take the "shutdown all services" functionality out of the WMS (e.g., create a Terminator service that is given some termination condition by the user)
  2. Make it possible to create a WMS that runs on a constrained set of services
  3. Add a "start time" to a WMS
  4. At this point should be easy to have concurrent WMS instances
  5. Then think about the WMS that can handle a stream of workflows

**Comment by rafaelfsilva** [comment]
Item 1-4 above have been implemented and tested. I believe item 5 (stream of workflows within a WMS) should be another feature. So, if there is no objection, I will close this issue and create a new one for item 5.

**Comment by henricasanova** [comment]
Sounds good to me.
