### ISSUE TITLE
Task states updated before notifications are received

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#56]
As I am writing WRENCH-based simulators,  I am noticing something: task states are updated before notifications are received. Task states are tricky, which is why I had a while back split the task state into "state" and "internal state". This was because, e.g., when a compute service sets a task state to completed, from the WMS's perspective the task is still pending until a notification is sent.  This has made things much easier, but now another but similar issue is coming up.  Here is a scenario:

1) A compute service sends back a "job done" notification to a job manager for task T
2) The job manager gets the notification and updates (non-internal) task states (i.e., T is now COMPLETED and some of T's children become READY)
3)  The job manager sends the notification to the WMS which will be an event

In the meantime, after 3) above but before the WMS does a waitForAndProcessNextEvent(), the WMS is doing something like: "hmmm... what tasks are ready again?"  And by looking at task states, it will see some of T's children as ready. It may even see T as completed. And then later, it will be told "task T has completed", although it already new that because it happened to look on its own at task states.

So far, in the simulators I've written, it's been weird in terms of the output I see (which caused me to wonder: "how could T's child be ready when T hasn't completed yet?", because I was only printing some "task completed" message upon receiving an actual event). For instance, by output could have been, for a T1->T2 workflow:
  - Submitting T1
  - T2 is ready
  - Submitting T2
  - T1 has completed!

which appears out-of-order, but it ok.

One question is : is this a bug or a feature? 

I am thinking bug because it seems more coherent to say that "task states cannot change arbitrarily in between job submissions/cancellations  and calls to waitForAndProcessNextEvent().  

The fix wouldn't be super straightforward, since right now the logic in the Job Manager is, as mentioned above: 

  1) Wait for a Job Completion (or Failure) message
  2) Update task states
  3) Send a message to the WMS (which will be caught by waitForAndProcessNextEvent())

So, now, 2) has to happen in the waitForAndProcessNextEvent() method, which is awkward...

anyway, something to discuss/think about.  Distributed computing, even in simulation, is never easy is it?

**Comment by rafaelfsilva** [comment]
I tend to agree with you that it is seems more like a bug. For example, in the HTCondor and DAGMan example, HTCondor updates the job internal state (i.e., the ClassAd), but DAGMan does not look into this state, instead it frequently queries the job states from HTCondor, and once a job is completed, then DAGMan updates the scheduler state (it would be the equivalent to our `getReadTasks()` function). 

So maybe a simple fix could be to change our `getReadTasks()` function to look at a different job state?

**Comment by henricasanova** [comment]
We already have the "internal state" vs. "visible state" feature implemented, and that works 99% great. In your example, indeed, the services only deal with the "internal state" (as they should), and only the job manager sets the "visible state" based on the "internal states".   The getReadyTasks() function looks at the "visible job state", which is fine.

The only question is "when should the job manager update the task visible states?".  And to fix this bug/behavior, the answer to that question " in the call to waitForAndProcessNextEvent().  

A fix could be as follows:
  - The job manager should not update task "visible states", but in the event message it sends to the WMS, it should encode what "visible state" updates should be made.
  - The WMS as usual calls waitForAndProcessNextEvent(), which in turns calls waitForNextExecutionEvent(), which right now does:
       1. call getMessage()
       2. return an Event based on message content
   and should do instead:
       1. call getMessage()
       2. update "visible states" based on message content
       3. return an Event based on (other) message content

So, in other terms, for a job completion, the compute service sends a StandardJobDone to the Job Manager. The Job Manager creates a new message, say,  EnhancedStandardJobDone that encodes all task state updates and sends it to the WMS. When the WMS calls waitForAndProcessNextEvent(), that method updates "visible states" based on the encoding in the EnhancedStandardJobDone message, and then generates the event as before, then calling the developer-provided callback.

I believe the above works..... but these are famous last words :)

**Comment by rafaelfsilva** [comment]
I agree that letting the WMS update the visible states seems to be the right solution here.

**Comment by henricasanova** [comment]
Ok. I'll create a branch and experiment with a solution along the lines above... we'll see what happens :)

**Comment by henricasanova** [comment]
Was easy-peasy. Just pushed the change to 1.0 and merged into master.
