### ISSUE TITLE
Evolve Virtualized Cluster Service

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#60]
Evolve VirtualizedClusterService so that it:
  - Allows a VM to be shutdown
  - Allows a job to be submitted to a particular VM

**Comment by rafaelfsilva** [comment]
Job submission to a particular VM can be done by providing the `wrench::CloudServiceProperty::JOB_MAPPING_TO_VM` property when submitting a job to the job manager (via the `std::map<std::string, std::string> service_specific_args` parameter).

I will soon update the documentation and then close this issue.

**Comment by rafaelfsilva** [comment]
Let's have a call about it :)
