### ISSUE TITLE
What's the difference between CloudService and VirtualizedClusterService?

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#61]
At this point in the code, these two services look pretty identical....

**Comment by rafaelfsilva** [comment]
It will become clearer once support to failures will be available. I will revisit this issue soon.

**Comment by henricasanova** [comment]
So I do see the difference, but I guess I am still a bit confused. I thought that the Cloud service would  never expose physical host names. So you would just say "create a VM" and the Cloud service would pick some physical host for you. And then you can just suspend/resume/shutdown the VM given its name. But I see that  createVM() takes a physical hostname, which I find confusing. The Cloud service implementation may of course decide to do migrations, like many cloud infrastructures do, but that's transparent. 

By contrast, on a VC service, one would say "create a VM on that particular host", and then you can do the migrate from one host to another. So the developer there is completely in charge of which VM runs on which host. In this way, Benjamin would be using a VC service, and not a cloud service.

I may be totally mistaken though :)

**Comment by rafaelfsilva** [comment]
This makes completely sense! I will update the methods accordingly.
