### ISSUE TITLE
StorageService: A a (configurable) small flop overhead for each file read

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#62]

**Comment by frs69wq** [comment]
I don't know if this can be helpful for this issue, but I recently modified the way IOs were handled by SimGrid to allow for asynchronous IOs. As for the Comm and Exec activities, you can now decompose a read in 
IoPtr  activity= init_io(size, Io::OpType::Read);
activity->start();
activity->wait();

Adding a small execute or sleep just after the start() of the IO activity might do the trick.

**Comment by henricasanova** [comment]
This is helpful, but as of now there is no IO at all in WRENCH, due to the “concurrent IO / Network” parallel task issue. But once we have IO, then that will be great. Right now, what looks as IO is just a network send/recv.

Henri

**Comment by henricasanova** [comment]
Thinking more about this, I think we should do something more general. Benjamin's concern was that a service would "do things" even though the host's pstate was 0.  This seems to be a concern for all kinds of services, not just storage services. So I am thinking of instead implementing an idea that Rafael initially proposed, but in all services. At each iteration of the main loop do something like:
    if (host compute speed == 0 flops/sec) {
         S4U_Simulation::execute(0.0001);
    }

This way, a service will be "stuck" until the host power is up again.

**Comment by henricasanova** [comment]
implemented a computeZeroFlops() method called before all actors' main() and at each daemon's iteration
