### ISSUE TITLE
Re-implement MultiHostMultiCoreComputeService as BareMetalComputeService

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench#76]
- no longer does resource allocation
  - service-specific arguments for job submission

**Comment by henricasanova** [comment]
The BareMetal service cannot support pilot jobs (Otherwise it would have to do resource allocation).  

@rafaelfsilva  This creates a problem for the CloudService as the cloud service seems to be using the MultihostMulticoreComputeService's PilotJob support.  Looking at the CloudService, I also see that only 1-host (or 1-vm) pilot jobs are supported.  As a result, the CLoudService doesn't really do resource allocation to the pilot job either. What would be useful is a multi-host pilot job, just like the batch service. But then I am also wondering, what's the point of PilotJobs for the CloudService.  Do clouds do pilot jobs? I don't think so... Should we just forget PilotJobs for the Cloud? And just have them for the BatchService?  Or for whatever system that does actual resource allocation as in "10 hosts at a time" (like Condor's Glide-In stuff for instance).

**Comment by henricasanova** [comment]
The implementation is finished, and branch baremetal_service has it all in it.  The plan is to merge it with master after the 1.2 release.

**Comment by rafaelfsilva** [comment]
@henricasanova Can we close this issue?

**Comment by henricasanova** [comment]
yes. closing it now.
