### ISSUE TITLE
Feature Request: dump pstate and energy consumption data as JSON

### ISSUE THREAD

**Issue by ryantanaka** [wrench-project/wrench#88]
Create a function (part of SimulationOutput) to dump host energy consumption data as JSON. As of now, the resulting JSON for this function looks like this:

```
[
    {
        hostname: <string>,
        pstates: [        <------ list of pstate settings (essentially whatever is specified in the platform file)
            {
                pstate: <int>,
                speed: <int>,
                idle: <int>,
                one_core: <int>,
                all_cores: <int>
            },
            ....
        ],
        watts_off: <int>,
        pstate_trace: [        <------ time series containing (timestamp, new pstate) tuples
            {
                 time: <double>,
                 pstate: <int>
            },
            ...
        ],
        consumed_energy_trace: [        <------ time series containing (timestamp, watts) tuples
            {
                 time: <double>,
                 watts: <double>
            },
            ...
        ]
    },
    ...
]
``` 

Some notes..

- regarding consumed_energy:
    - as of now this will only contain total consumed energy from the time the simulation starts until it ends (a single entry in the list)
    - we could implement some type of service that captures consumed energy at some specified time interval 

- regarding changes in pstate_trace:
    - when `static void setPstate(std::string hostname, int pstate)`, I can set a timestamp so that we have a trace
    - for the initial pstate, if `pstate` is set in the platform file for a host, there doesn't appear to be any simgrid call like simgrid::s4u::Host::getInitialPstate(). Instead, we would have to, in S4U_Simulation::launch(), before calling SimGrid::launch(), for each host get its initial pstate by calling getCurrentPstate() (we tested this and it works). 
    - if no initial pstate is set in the platform file, the host defaults to using whatever pstate 0 is

**Comment by ryantanaka** [comment]
@henricasanova, In a test I wrote for the `EnergyMeter`, I'm getting some weird behavior and I'm not sure what is going on. The test runs nicely 90% of the time and passes, but sometimes it hangs and I need to `CTRL-C` the test (see output bellow). 
```
Note: Google Test filter = SimulationTimestampEnergyTest.EnergyMeterSingleMeasurementPeriodTest
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from SimulationTimestampEnergyTest
[ RUN      ] SimulationTimestampEnergyTest.EnergyMeterSingleMeasurementPeriodTest
[0.000000][host1:energy_meter_5(2)] New Energy Meter Manager starting (energy_meter_5)
^C[0.000000][host1:energy_meter_5(2)] CTRL-C pressed. The current status will be displayed before exit (disable that behavior with option 'verbose-exit').
[0.000000][host1:energy_meter_5(2)] 2 processes are still running, waiting for something.
[0.000000][host1:energy_meter_5(2)] Legend of the following listing: "Process <pid> (<name>@<host>): <status>"
[0.000000][host1:energy_meter_5(2)] Process 1 (wms_test_1@host1)
[0.000000][host1:energy_meter_5(2)] Process 2 (energy_meter_5@host1)
[0.000000][host1:energy_meter_5(2)]
[0.000000][host1:energy_meter_5(2)] The time is still 0, and you still have processes ready to run.
[0.000000][host1:energy_meter_5(2)] It seems that you forgot to run the simulation that you setup.
[0.000000][host1:energy_meter_5(2)] Bailing out to avoid that stop-before-start madness. Please fix your code.
[ ABORTING ]
```

This didn't start happening until I added the below segment of code to start testing `createEnergyMeter()` (so I can test for the exceptions in the EnergyMeter constructor).

https://github.com/wrench-project/wrench/blob/ef6f86e1100ba9118f0fba195b5015ceac735091/test/simulation/simulation_output/SimulationTimestampEnergyTest.cpp#L255-L298

Any idea what's happening?

**Comment by rafaelfsilva** [comment]
@ryantanaka BTW, I did a commit (2ebb431) yesterday night to fix a small issue I was having with the creation of the EnergyMeter, not sure that it might affect your tests.
